### ISSUE TITLE
service-groups internal server error

### ISSUE THREAD

**Issue by hemebond** [shinken-monitoring/mod-webui#282]
Error occurs on /services-groups. If necessary I can try and cut down my config to test with.

# Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:7767/services-groups' caused an error:

```Internal Server Error```

## Exception:
```AttributeError("'Service' object has no attribute 'get_servicegroups'",)```

## Traceback:
```
Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 391, in lock_version
    return f(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui/plugins/groups/views/services-groups-overview.tpl", line 107, in <module>
    %services = app.datamgr.search_hosts_and_services('type:service sg:'+group.get_name(), user)
  File "/var/lib/shinken/modules/webui/datamanager.py", line 316, in search_hosts_and_services
    items = [i for i in items if group in i.get_servicegroups()]
AttributeError: 'Service' object has no attribute 'get_servicegroups'
```

**Comment by maethor** [comment]
Indeed, this method is missing in the Service class. I'll fix it, thank you.
