### ISSUE TITLE
Graph Widget don't work for me

### ISSUE THREAD

**Issue by monito-git** [shinken-monitoring/mod-webui#292]
Hi,

I don't understand because, my graphite graphs work in the host or service view but not in the dashboard.
I have the folowing message : "Error loading this widget:"
When I restart shinken I can add an empty widget graphs (No graph for this element.) but after the first shinken check I have "Error loading this widget."

In brief, it seems the widget graphs can't display a graphite graph ...

Someone can help me ? 

Thanks

PS : With the official webui the graph widget works.

**Comment by maethor** [comment]
Hello @monito-git. What version of the webui are you using? The BS3 branch, or the WebUI installed from shinken-io? What did you mean by "the official webui"?

Widgets in general may not work well. But I'm currently working on graphs, so I'll take a look at the widget.

**Comment by monito-git** [comment]
Thanks for your answer maethor.
I use the BS3 and by "the official webui" I would like mean the webui from shinken-io.

In my webui, all widgets work well expect the graph.

**Comment by monito-git** [comment]
I completely reinstall the webui.
* 1st Step : Reinstall the webui from shinken.io (all work well)
* 2nd Step : Install the bs3 branch with this commands 
```
    $  git clone -b bs3 https://github.com/shinken-monitoring/mod-webui
    $  sudo shinken install --local mod-webui
```

I can log me with admin / admin but after I have the error bellow : 
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://192.168.1.40:7767/dashboard' caused an error:

Internal Server Error
Exception:

ServerSelectionTimeoutError('localhost:27017: [Errno 111] Connection refused',)
Traceback:

Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 392, in lock_version
    return f(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui/plugins/dashboard/dashboard.py", line 49, in get_page
    s = app.prefs_module.get_ui_user_preference(user, 'widgets')
  File "/var/lib/shinken/modules/webui/submodules/prefs.py", line 41, in get_ui_user_preference
    return self.module.get_ui_user_preference(user, key) or default
  File "/var/lib/shinken/modules/webui/submodules/prefs.py", line 166, in get_ui_user_preference
    e = self.db.ui_user_preferences.find_one({'_id': user.get_name()})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 728, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

In my broker_log there are 2 errors : 
```
[1439456747] ERROR: [broker-master] [WebUI] loading plugin graphs, exception: No module named requests

[1439456777] ERROR: [broker-master] [WebUI] loading plugin worldmap, exception: localhost:27017: [Errno 111] Connection refused
```

I think before I didn't use the Bsr Branch but the BS3 pre-release.

I don't know how solve this problem :(

**Comment by maethor** [comment]
Hm, this is not related to this issue. But it seems I forget to add a dependency in the requirements.txt. You can fix this by installed requests  with `sudo pip install requests` (or `sudo aptitude install python-requests`, or `rpm something`).

Sorry about that. I was sure that requests was already a dependency of the webui.

**Comment by monito-git** [comment]
Thanks you for your quick answer maethor, I used pip ! The webui is now fine :)

But Graph Widget always don't work and now I can't edit or delete a widget with button on the top right corner of widget panel.

![image](https://cloud.githubusercontent.com/assets/13745844/9247694/905d8d06-41b5-11e5-8017-e20f8811c3d2.png)

**Comment by maethor** [comment]
Hum. Please report another issue for this deletion problem. @mohierf will take a look in a few days.

**Comment by monito-git** [comment]
After my lunchtime deletion problem disappeared without I do anything. Maybe web cache or maybe karma. Sorry for this false alerte.

The initial issue with Graph Widget is still here.

PS : Sorry maethor, next time I will post each issue on seperate topic. Github is a new thing for me.

**Comment by maethor** [comment]
No problem! It's very nice of you to come here and report your bugs. I promise I'll try to debug the graph widget when I find some time.

**Comment by maethor** [comment]
@monito-git can you confirm that the bug is closed with the last version of the webui?

**Comment by monito-git** [comment]
Thanks @maethor, good job ! I can now load the graph widget so this bug is closed :)
I will open an other issue to improve this widget.

![image](https://cloud.githubusercontent.com/assets/13745844/9271027/ccbcd9ca-4276-11e5-965e-e6cdcdf7034e.png)
