### ISSUE TITLE
BS3 - can't work with shinken 2.4.1

### ISSUE THREAD

**Issue by hvad** [shinken-monitoring/mod-webui#293]
Hi,

After install bs3 like that : 
git clone -b bs3 https://github.com/shinken-monitoring/mod-webui
shinken install --local mod-webui

I can't acces to webui BS3. 

I saw in log : 

[1439383554] WARNING: [broker-master] Cannot import webui : No module named webui
[1439383554] WARNING: [broker-master] Cannot import webui..module : No module named webui.module
[1439383554] WARNING: [broker-master] Trying to load '/var/lib/shinken/modules/webui' as an (very-)old-style shinken "module" : by adding its path to sys.path. This can be (very) bad in case of name conflicts within the files part of /var/lib/shinken/modules/webui and others top-level python modules; I'll try to limit that.
[1439383554] ERROR: [broker-master] Could not import bare 'module.py' from /var/lib/shinken/modules/webui : No module named module
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named module

[1439383554] WARNING: [broker-master] The module type webui for webui was not found in modules!

I don't know why broker can't load webui module. 

Any idea ? Bug ? 

Best regard

**Comment by maethor** [comment]
Is the webui really installed? Do you have the file `/var/lib/shinken/modules/webui/module.py`?

**Comment by hvad** [comment]
Yes file is present.

**Comment by mohierf** [comment]
@hvad : does the problem still exists ? did you made more tests with Shinken 2.4.1 ?

**Comment by hvad** [comment]
Hi,

Sorry i not had time to complete test. I try to test soon.

Regard

**Comment by mohierf** [comment]
@hvad : some news about it ? I and @maethor are really interested in your feedback to make sure that our new version is fully ok with Shinken 2.4.1 ...

**Comment by hvad** [comment]
Hi,

I try to install BS3 again and i had this message when i restart : 

[1441290890] ERROR: [Shinken] [WebUI-MongoDBPreferences] Can not import pymongo and/or MongoClientYour pymongo lib is too old. Please install it with a 3.x+ vers
ion from https://pypi.python.org/pypi/pymongo
[1441290890] ERROR: [Shinken] Could not import bare 'module.py' from /var/lib/shinken/modules/webui : No module named pymongo
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib/python2.6/site-packages/importlib-1.0.2-py2.6.egg/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/shinken/modules/webui/module.py", line 62, in <module>
    from submodules.prefs import PrefsMetaModule
  File "/var/lib/shinken/modules/webui/submodules/prefs.py", line 68, in <module>
    import pymongo
ImportError: No module named pymongo

Now BS3 is not compatible with pymongo version 2.5.

**Comment by hvad** [comment]
I don't found how disable pymongo for BS3.

**Comment by mohierf** [comment]
Is it a problem to you to install a recent pymongo library ?

Anyway, I think it may be interesting to catch the exception properly :/P

**Comment by mohierf** [comment]
I just tested and if you comment this line: https://github.com/shinken-monitoring/mod-webui/issues/293#issuecomment-137468859, the WebUI will start properly and the WebUI preferences features will simply be disabled. 

I will commit a clean fix for this later.

**Comment by mohierf** [comment]
@maethor : any idea how to cath this properly ... disabling the `raise` allows to start the WebUI but there are still many logs each time we try to use the preferences meta-module :/P

**Comment by maethor** [comment]
Why did you move this import out of the MongoDBPreferences class ? This problem is exactly why I put the import in the class.

I will fix it.

Thanks for testing @hvad. Also, you should really use mongodb to have access to all the features of the new shinken webui.

**Comment by mohierf** [comment]
You are right @maethor ... the import should be inside the class ... I do not remember ... but we already did fixed this several weeks ago! Or, perharps, in another module ...

**Comment by hvad** [comment]
Sorry, my bad. I forgot python-pymongo on my server.

**Comment by mohierf** [comment]
@maethor : pymongo is imported outside the class but you imported MongoClient inside the class. I will fix ...
