### ISSUE TITLE
problem with system/logs

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#296]
Hi,
I made a mistake with  the system/logs, I unselect all options in parameters : the result is the message bellow...
Now I can't go back, how reset logs parameters ? Is it possible to doesn't save the parameters ? or testing the choice before save ?

Thanks

Error: 500 Internal Server Error
Sorry, the requested URL 'http://XXX.XXX.XXX.XXX:7767/logs' caused an error:
Internal Server Error
Exception:
TypeError("object of type 'NoneType' has no len()",)
Traceback:
Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 392, in lock_version
    return f(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui/plugins/logs/logs.py", line 150, in get_global_history
    if len(logs) > 200:
TypeError: object of type 'NoneType' has no len()

**Comment by mohierf** [comment]
In the plugin directory (*webui/plugins/logs*), you will find a `plugin.cfg` file in which you may specify which logs type are to be displayed : 
```
# Filter for these log types (leave empty for no filtering)
#logs_type=PASSIVE HOST CHECK, HOST NOTIFICATION, PASSIVE SERVICE CHECK, SERVICE NOTIFICATION
logs_type=INFO,WARNING,ERROR
```

**Comment by maethor** [comment]
Indeed, this was a pretty bug. My mistake.

My commit should fix your problem.
