### ISSUE TITLE
authentification

### ISSUE THREAD

**Issue by rom1701** [shinken-monitoring/mod-webui#317]
i think since this commit 73a9ae24820c02054444d6fe5a97928940319347 in datamanger i can not login:
[1441284729] INFO: [broker-lyo2-shinken-core00] [WebUI]  user 'toto' is signing in ...
[1441284729] INFO: [broker-lyo2-shinken-core00] [WebUI] Checking authentication for user: toto
[1441284729] ERROR: [broker-lyo2-shinken-core00] [WebUI] You need to have a contact having the same name as your user: toto
[1441284729] WARNING: [broker-lyo2-shinken-core00] [WebUI]  user 'toto' access denied

**Comment by maethor** [comment]
Do you have a contact named "toto" ?

**Comment by rom1701** [comment]
Yes, i try to understand this problem, i use auth_htpasswd, and when i want to log me, never this module is call, and my bad for my think about your commit, i was try with an older version, and i have a same problem. When i run the debug, i see my contact in the debug log. I don't know why get_contact return nothing.

**Comment by rom1701** [comment]
sorry, get_contact return "None"

**Comment by maethor** [comment]
I understand that, but do you have a contact object named "toto" in your configuration? Can you copy it here please?

**Comment by rom1701** [comment]
define contact{
    use             generic-contact
    contact_name    toto
    email           toto@local.fr
    is_admin        1
}

define contact{
     name generic-contact
     host_notifications_enabled 1
     service_notifications_enabled 1
     can_submit_commands 1
     notificationways email
     register 0
}

**Comment by rom1701** [comment]
I found it, sorry, my bad, in my webui.cfg I had:
 modules     auth-htpasswd # ,ui-graphite,mongodb,mongo-logs

for test auth-htpasswd module only, and i was no see in log shinken don't take auth-htpasswd module.

**Comment by rom1701** [comment]
after more investigation, if i have in webui.cfg:  modules     auth-htpasswd it's works
but if i have: modules     auth-htpasswd, ui-graphite (or other module) i have this problem
or modules     auth-htpasswd,ui-graphite the same

**Comment by mohierf** [comment]
If I summarize, the `auth-htpasswd`module is authenticating correcty only when it is the only declared module ?

**Comment by rom1701** [comment]
yes

**Comment by maethor** [comment]
Hm… This is odd.

**Comment by maethor** [comment]
@mohierf are you using an authentification module? I do not myself…

**Comment by mohierf** [comment]
I am testing currently ...

**Comment by mohierf** [comment]
I made tests with some authentication modules in the WebUI.

With the new meta-module implemented in the WebUI, none of the authentication modules is able to log some information in the main `brokerd.log` file ... which makes it quite uncomfortable to test :/P

But I logged in with 

```
[1441297195] INFO: [broker-master] [WebUI] starting Web UI server ...
[1441297208] INFO: [broker-master] [WebUI]  user 'admin' is signing in ...
[1441297208] INFO: [broker-master] [WebUI] Checking authentication for user: admin
[1441297208] INFO: [broker-master] [WebUI] Authenticating user 'admin' with auth-cfg-password
[1441297208] INFO: [broker-master] [WebUI] User 'admin' is authenticated by auth-cfg-password
[1441297208] INFO: [broker-master] [WebUI] User picture: /static/photos/admin
[1441297208] INFO: [broker-master] [WebUI]  user 'admin' signed in
[1441297221] INFO: [broker-master] [WebUI]  user 'admin' signed out
[1441297235] INFO: [broker-master] [WebUI]  user 'mohier' is signing in ...
[1441297235] INFO: [broker-master] [WebUI] Checking authentication for user: mohier
[1441297235] INFO: [broker-master] [WebUI] Authenticating user 'mohier' with auth-cfg-password
[1441297235] INFO: [broker-master] [WebUI] Authenticating user 'mohier' with auth-ws-glpi
[1441297235] WARNING: [broker-master] [WebUI] The user 'mohier' has not been authenticated.
[1441297235] WARNING: [broker-master] [WebUI]  user 'mohier' access denied
[1441297259] INFO: [broker-master] [WebUI]  user 'mohier' is signing in ...
[1441297259] INFO: [broker-master] [WebUI] Checking authentication for user: mohier
[1441297259] INFO: [broker-master] [WebUI] Authenticating user 'mohier' with auth-cfg-password
[1441297259] INFO: [broker-master] [WebUI] Authenticating user 'mohier' with auth-ws-glpi
[1441297259] INFO: [broker-master] [WebUI] User 'mohier' is authenticated by auth-ws-glpi
[1441297259] INFO: [broker-master] [WebUI] User picture: /static/photos/mohier
[1441297259] INFO: [broker-master] [WebUI]  user 'mohier' signed in
```

**Comment by mohierf** [comment]
@maethor : I think I found the problem!

My tests made me think about an interesting feature: embed apache htpasswd authentication in the Web UI authentication module ... it simply implies to add a configuration parameter for locating the `htpasswd.user` file and it will avoid to install an extra module ...

Waiting for your return ...

**Comment by maethor** [comment]
I totally agree. But it doesn't mean you found the problem. You just found a workaround ;D

**Comment by mohierf** [comment]
Not sure I found the real problem met by  @rom1701 ... but I thoroughly tested the authentication process and everything is ok on my configuration. Still some few tests and I will commit ...

I made tests with (and without) `auth-cfg-password`, `auth-htpasswd`, `auth-ws-glpi` and with embedded authentication (config and htpasswd).

What I noticed when you are using `auth-htpasswd` module is that the passwords file declared in the module configuration must be accessible by the user `shinken`. Is it true for you @rom1701 ?

**Comment by rom1701** [comment]
yes i confirm.
For information,  when auth-htpasswd is not alone in webui configuration, never i see log about auth-htpasswd.

**Comment by mohierf** [comment]
You should get the last commit I pushed this morning and test if it is ok on your configuration. Mine is ok ...

**Comment by rom1701** [comment]
I have a problem with your commit, when i want restart shinken i have the error:
[1441356372] ERROR: [Shinken] Could not import bare 'module.py' from /usr/share/pyshared/shinken/modules/webui : No module named md5crypt
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/pyshared/shinken/modules/webui/module.py", line 63, in <module>
    from submodules.auth import AuthMetaModule
  File "/usr/share/pyshared/shinken/modules/webui/submodules/auth.py", line 7, in <module>
    from lib.md5crypt import apache_md5_crypt, unix_md5_crypt
ImportError: No module named md5crypt

**Comment by mohierf** [comment]
I just commited a missing file ... sorry for the problem. My git tools was badly configured :/P

**Comment by rom1701** [comment]
if i have a module, i have the same problem, if i don't have module, it's works

**Comment by rom1701** [comment]
When it's works:

INFO: [broker-shinken00] [WebUI] Checking authentication for user: toto
INFO: [broker-shinken00] [WebUI] Requesting authentication for user: toto
INFO: [broker-shinken00] [WebUI] Authenticating user 'toto'
INFO: [broker-shinken00] [WebUI] Embedded authentication for 'toto'
INFO: [broker-shinken00] [WebUI-auth-cfg-password] Authenticating user 'toto'
WARNING: [broker-shinken00] [WebUI-auth-cfg-password] Authentication failed
INFO: [broker-shinken00] [WebUI-auth-htpasswd] Authenticating user 'toto'
INFO: [broker-shinken00] [WebUI-auth-htpasswd] Authenticated
INFO: [broker-shinken00] [WebUI] User 'toto' is authenticated by htpasswd password 
INFO: [broker-shinken00] [WebUI] User picture: /static/photos/toto 
INFO: [broker-shinken00] [WebUI]  user 'toto' signed in 

when failed:

INFO: [broker-shinken00] [WebUI]  user 'toto' is signing in ... 
INFO: [broker-shinken00] [WebUI] Checking authentication for user: toto 
ERROR: [broker-shinken00] [WebUI] You need to have a contact having the same name as your user: toto
WARNING: [broker-shinken00] [WebUI]  user 'toto' access denied

**Comment by mohierf** [comment]
With this log, I understand that, when you have a module, the WebUI do not recognize `toto` as a contact and then do not even try to authenticate it ...

On my installation, it works even if I have a module! I tried to produce the same problem but never succeeded ... 

Suggestions:
- your authentication modules are up to date ?
- do you have some ERROR logs when launching the broker ?
- launch the broker in debug mode to have more lines in your log ?

**Comment by rom1701** [comment]
my authentication modules are up do date, i have no more log in debug mode about authentication. and when i start the broker, i have only one error, but i think is not important:

ERROR: [broker-shinken00] [WebUI] loading plugin graphs, exception: No module named requests

**Comment by mohierf** [comment]
If you installed the auth-htpasswd you may have some logs in debug mode ... on init, this module logs this information: 
```
[Auth htpasswd] Connection test to the Apache/Passwd file
```

Not sure it may be helpful, but you should install the python `requests` module :-)

**Comment by rom1701** [comment]
yes i have:
INFO: [broker-shinken00] [Auth htpasswd] Instantiate an Apache/Passwd UI module for plugin auth-htpasswd 
and 
INFO: [broker-shinken00] Correctly loaded auth-htpasswd as an old-new-style shinken module :|

ok, thanks for your help, i will install the python requests module

**Comment by mohierf** [comment]
Sorry but I do not see more tests to understand your modules problem ... I cannot reproduce it!

A last idea: do you see your contact `toto`in the contacts page of the WebUI ?

**Comment by rom1701** [comment]
i have remove all module of webui, and install and now it's works...

**Comment by b-keller** [comment]
Hi, 
Same problem of authentification with webui 2.0.1 install... 

- centos 7 fresh install
- install shinken 2.4 with its requirements ok
- install requirements for webui2 ok 
- install modules : 
```
shinken install mongo-logs
shinken install webui2
```
modif config files : 
/etc/shinken/brokers/broker-master.cfg
```modules     webui2```
/etc/shinken/modules/webui2.cfg
```modules mongo-logs```
/etc/shinken/modules/mongo-logs.cfg
```hav_collection      availability```

If I understood correctly, Webui2 embedded its own authentification plugin. So I don't install "auth-cfg-password".

default contact "admin" exist with default password
When I want to login, webui return the message : "Warning! Invalid user or Password"
in the broker log : 
 ```
[1442148888] INFO: [broker-master] [WebUI]  user 'admin' is signing in ...
[1442148888] INFO: [broker-master] [WebUI] Checking authentication for user: admin
[1442148888] ERROR: [broker-master] [WebUI] You need to have a contact having the same name as your user: admin
[1442148888] WARNING: [broker-master] [WebUI]  user 'admin' access denied
```
I made the same test without "auth-htpasswd" : 
``` htpasswd -c /etc/shinken/htpasswd.users admin```
Same message on webui and in broker log.

Shinken debug mode don't give me more informations...

I missed something ?
