### ISSUE TITLE
Webui2 - log rotation and error 500

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#368]
Hello,

 Since I put log module into webui I have an error which appeared after , what it seems, system log rotation : 

```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://shinken.freesquare.org:17767/logs' caused an error:

Internal Server Error

Exception:

TypeError("'NoneType' object is not iterable",)

Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/logs/views/logs.tpl", line 134, in <module>
    %for log in records:
TypeError: 'NoneType' object is not iterable
```
 if I play : 
```
service shinken-arbiter reload
```
I can reach the log page again but without previous lines inside from the log before the incident.

  Regards,

**Comment by mohierf** [comment]
Fixed in develop branch, will be in the next version
