### ISSUE TITLE
/user/pref 500 (With SQLite)

### ISSUE THREAD

**Issue by zoneroot** [shinken-monitoring/mod-webui#371]
Hello, when i try to go on /user/pref page with sqlite database I have a 500 error with exception
```
TypeError("'NoneType' object is not iterable",)
```
and traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/user/views/user_pref.tpl", line 95, in <module>
    %for preference in app.prefs_module.get_ui_user_preference(user):
TypeError: 'NoneType' object is not iterable
```
When I try with mongodb this page works.
I have installed mongodb with `pip` and webui2 with `shinken install` on debian 7.7.

**Comment by maethor** [comment]
Hello @zoneroot 

Like documented here : https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-storage-modules

> The sqlite module is not documented, has not been tested and should not be used except if you know exactly what you are doing. Please notice that no support will be provided if you use this module. Some information may be found in the Shinken documentation if needed. 

So thank you, now we are sure it doesn't work :)
