### ISSUE TITLE
auth-active-directory module not working with Webui2

### ISSUE THREAD

**Issue by agapoff** [shinken-monitoring/mod-webui#373]
I have included the module in webui2.cfg:
modules auth-active-directory

But webui2 does not use it for authentication as webui did.

This is an excerpt from brokerd.log

INFO: [broker-master] [WebUI]  user 'username' is signing in ...
INFO: [broker-master] [WebUI] Checking authentication for user: username
INFO: [broker-master] [WebUI] Requesting authentication for user: username
INFO: [broker-master] [WebUI] Authenticating user 'username'
INFO: [broker-master] [WebUI] Embedded authentication for 'username'
INFO: [broker-master] [WebUI-auth-cfg-password] Authenticating user 'username'
WARNING: [broker-master] [WebUI-auth-cfg-password] Authentication failed
INFO: [broker-master] [WebUI-auth-htpasswd] Authenticating user 'username'
WARNING: [broker-master] [WebUI] The user 'username' has not been authenticated.
WARNING: [broker-master] [WebUI]  user 'username' access denied

**Comment by mohierf** [comment]
Is it possible that you copy the brokerd.log part containing the WebUI start and module loading ? We will be able to see if the module is correctly loaded and if WebUI will use it for authentication.

For example, this log line for the Glpi authentication module: 
``
[1445435580] INFO: [broker-master] [WebUI] Module found: auth-ws-glpi
``

I made a test and simply installed the `auth-active-directory` module and included it in webui2.cfg, but when I restarted Shinken I had an exception because of missing `python-ldap`! This problem can not be detected with the part of log you copied ...

**Comment by agapoff** [comment]
Here is a part with module loading. I haven't found anything about auth-active-directory here. The only suspicious line is "No module for AuthMetaModule".

```
INFO: [broker-master] Trying to init module: webui2
INFO: [broker-master] [WebUI] got an instance of Webui_broker for module: webui2
INFO: [broker-master] [WebUI] Initializing ...
INFO: [broker-master] Starting external module webui2
INFO: [broker-master] Starting external process for instance webui2
INFO: [broker-master] webui2 is now started ; pid=14343
INFO: [broker-master] Trying to init module: livestatus
INFO: [broker-master] [webui2[14343]]: Now running..
INFO: [broker-master] Modules directory: /var/lib/shinken/modules
...
INFO: [broker-master] Correctly loaded webui2 as an old-new-style shinken module :|
INFO: [broker-master] Correctly loaded auth-active-directory as an old-new-style shinken module :|
INFO: [broker-master] [WebUI] No module for AuthMetaModule.
...
INFO: [broker-master] [WebUI] No module for GraphsMetaModule. You should configure the module 'graphite' in your broker and the module 'ui-graphite' in webui.cfg file to be able to display graphs.
INFO: [broker-master] [WebUI] load plugins directory: /var/lib/shinken/modules/webui2/plugins
INFO: [broker-master] [WebUI] loaded plugin dummy
... some plugins loading is skipped
INFO: [broker-master] [WebUI] loaded plugin problems
INFO: [broker-master] [WebUI] starting Web UI server ...
```

**Comment by agapoff** [comment]
The whole brokerd.log can be seen here: http://pastebin.com/tz58D23F

**Comment by mohierf** [comment]
The `No module for AuthMetaModule` says clearly that the module has not been loaded ... which is confirmed with `[1445422930] INFO: [broker-master] I correctly loaded the modules: []` as an empty module list! The only thing I may say is that the ldap module has encountered a problem and did not initialized correctly ... but I can not be of more help because I never used this module :/P

 You hould try to open an issue in the module repo ?

On my testing configuration, with a fresh module installation, I got this in the log:
 ``
[1445441426] INFO: [broker-master] Trying to init module: ui-graphite
[1445441426] INFO: [broker-master] Trying to init module: auth-active-directory
[1445441426] INFO: [broker-master] Trying to init module: auth-ws-glpi
[1445441426] INFO: [broker-master] [Auth WS Glpi] Connecting to Glpi ...
[1445441426] INFO: [broker-master] [Auth WS Glpi] Connection opened
[1445441426] INFO: [broker-master] I correctly loaded the modules: [ui-graphite,auth-active-directory,auth-ws-glpi]
``

Which confirms that the module loaded and is known by the WebUI.

---
Please note that you have a problem with `mongo-logs` module:
``
[1445422931] ERROR: [broker-master] [WebUI-mongo-logs] Exception: Unknown option connect
``
Probably because of an incompatible pymongo version. Did you installed pymongo 3 ?

**Comment by hogsim** [comment]
Hi, 
got the same problem. I installed python-ldap who seems to solve problem. But then i get this error message : 

[1445602818] INFO: [broker-master] [WebUI]  user 'smh' is signing in ...
[1445602818] INFO: [broker-master] [WebUI] Checking authentication for user: smh
[1445602818] INFO: [broker-master] [WebUI] Requesting authentication for user: smh
[1445602818] INFO: [broker-master] [WebUI] Authenticating user 'smh'
[1445602818] INFO: [broker-master] [WebUI] Authenticating user 'smh' with auth-active-directory
[1445602818] WARNING: [broker-master] [WebUI] The mod auth-active-directory raised an exception: {'info': '80090308: LdapErr: DSID-0C0903C8, comment: AcceptSecurityContext error, data 52e, v2580', 'desc': 'Invalid credentials'}, I'm tagging it to restart later
[1445602818] WARNING: [broker-master] [WebUI] Exception type: <class 'ldap.INVALID_CREDENTIALS'>
[1445602818] WARNING: [broker-master] Back trace of this kill: Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui2/submodules/auth.py", line 27, in check_auth
    if mod.check_auth(user, password):
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 229, in check_auth
    elts = self.find_contact_entry(c)
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 134, in find_contact_entry
    self.connect()
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 111, in connect
    self.con.simple_bind_s(self.username, self.password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 208, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'info': '80090308: LdapErr: DSID-0C0903C8, comment: AcceptSecurityContext error, data 52e, v2580', 'desc': 'Invalid credentials'}

[1445602818] INFO: [broker-master] [WebUI] Embedded authentication for 'smh'
[1445602818] INFO: [broker-master] [WebUI-auth-cfg-password] Authenticating user 'smh'
[1445602818] WARNING: [broker-master] [WebUI-auth-cfg-password] Authentication failed
[1445602818] INFO: [broker-master] [WebUI-auth-htpasswd] Authenticating user 'smh'
[1445602818] WARNING: [broker-master] [WebUI] The user 'smh' has not been authenticated.
[1445602818] WARNING: [broker-master] [WebUI]  user 'smh' access denied
[1445602819] INFO: [broker-master] Trying to init module: auth-active-directory


And I know my credentials are correct. Has someone the same issue?

**Comment by mohierf** [comment]
The problem is clearly in the `auth-active-directory` module which raises an exception that is catched by the WebBUI because it started the module ... you should open an issue in the module repository: https://github.com/shinken-monitoring/mod-auth-active-directory/issues

**Comment by hogsim** [comment]
Ok thanks, i will do it

**Comment by Wicaeed** [comment]
Might be worth to note that I was able to fix this by changing my auth username from a simple username to a `username@<addomain.tld>` format

**Comment by mohierf** [comment]
Thanks @Wicaeed 

@agapoff : do this solution solve your problem ?

**Comment by agapoff** [comment]
@mohierf I don't have an AD domain. I am using OpenLDAP.

Anyway seems like WebUI2 does not even try to load auth-active-directory module. The only concern is that @hogsim example shows the different behaviour despite I have python-ldap installed too.

**Comment by mohierf** [comment]
@agapoff : can you restart your broker and copy your `brokerd.log | grep WebUI` ?

**Comment by agapoff** [comment]
I have finally got it working but still don't know what was the cause. I've made many things: installed 2.4.2 shinken core, upgraded all python modules including pymongo (to v.3.0.3), restarted everything several times and at some moment the auth module started to load and I was able to login. So I think this issue can be closed.

Thank you for your help.

**Comment by Method68** [comment]
Hi, after install auth-active-directory, i configure auth_active_directory.cfg

define module {
    module_name     auth-active-directory
    module_type     ad_webui
    ldap_uri        ldaps://ldap.slash16.local
    username        cn=admin,dc=slash16,dc=local
    password        secret
    basedn          dc=slash16,dc=local

    # For mode you can switch between ad (active dir)
    # and openldap
    mode	    openldap
}

and

---------------webui2.cfg----------------

define module {
    module_name     auth-active-directory
    module_type     ad_webui
    ldap_uri        ldaps://ldap.slash16.local
    username        cn=admin,dc=slash16,dc=local
    password        secret
    basedn          dc=slash16,dc=local

    # For mode you can switch between ad (active dir)
    # and openldap
    mode	    openldap
}
admin2@Groupe55_2:/etc/shinken/modules$ cat webui2.cfg
## Module:      WebUI
## Loaded by:   Broker
# The Shinken web interface and integrated web server.
define module {
   module_name         webui2
   module_type         webui2

   modules    	       	  auth-active-directory

   host                       0.0.0.0      #; All interfaces = 0.0.0.0
   port                       7767
   ..........

-------------------brokerd.log---------------------

1495119242] INFO: [broker-master] [WebUI] Requesting authentication for user: vroche
[1495119242] INFO: [broker-master] [WebUI] Authenticating user 'vroche'
[1495119242] INFO: [broker-master] [WebUI] Internal htpasswd authentication
[1495119242] INFO: [broker-master] [WebUI] Internal alignak backend authentication
[1495119242] INFO: [broker-master] [WebUI] Internal contact authentication
[1495119242] INFO: [broker-master] [WebUI-auth-cfg-password] Authenticating user 'vroche'
[1495119242] ERROR: [broker-master] [WebUI-auth-cfg-password] You need to have a contact having the same name as your user: vroche
[1495119242] WARNING: [broker-master] [WebUI] The user 'vroche' has not been authenticated.
[1495119242] WARNING: [broker-master] [WebUI]  user 'vroche' access denied, redirection to: /user/login?error=Invalid user or Password
[1495119242] WARNING: [broker-master] [WebUI] login page with error message: Invalid user or Password

i don't understand how to call auth_active_directory for ldap connexion !

Thanks for any help.
