### ISSUE TITLE
Minemap : UnicodeEncodeError with unicode in service name

### ISSUE THREAD

**Issue by efficks** [shinken-monitoring/mod-webui#380]
I've got an exception when the service name contains unicode caracters.

```UnicodeEncodeError('ascii', u'Server - D\xe9marr\xe9', 13, 14, 'ordinal not in range(128)')```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/minemap/views/minemap.tpl", line 146, in <module>
    %s = app.datamgr.get_service(r, c, user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 242, in get_service
    sdesc = sdesc.decode('utf8', 'ignore')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)
```

**Comment by mohierf** [comment]
You have this exception only in minemap page or on all pages where this service is referenced ?

**Comment by efficks** [comment]
Only on the minemap

Le mer. 28 oct. 2015 12:44, Frédéric MOHIER <notifications@github.com> a
écrit :

**Comment by gst** [comment]
```
# this is bare python2: 
>>> '\xe9'.decode('utf8', 'ignore')
u''
>>> u'\xe9'.decode('utf8', 'ignore')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)
>>> 
```

Summary/conclusion : the `sdesc` in : 
```
File "/var/lib/shinken/modules/webui2/datamanager.py", line 242, in get_service
    sdesc = sdesc.decode('utf8', 'ignore')
```
is already unicode, so it's quite useless (and even harmful as we can see) to *decode* it..

a plausible workaround would be to do:
`sdesc = (sdesc if isinstance(sdesc, unicode) else sdesc.decode('utf8')`
but that's only a workaround for this very specific case.

**Comment by mohierf** [comment]
Thanks @gst ... you are right, it is only a workaround. We never in shinken if strings are encoded or not :/P
