### ISSUE TITLE
minemap error 500

### ISSUE THREAD

**Issue by hvad** [shinken-monitoring/mod-webui#410]
Hi,

Minemap don't work on fresh install webui2 via shinken install webui2 (requirement are installed). 

I saw this message on webui : 

Error: 500 Internal Server Error

Sorry, the requested URL 'http://127.0.0.1:7767/minemap' caused an error:

Internal Server Error

Exception:

AttributeError("'module' object has no attribute 'Counter'",)

Traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 418, in lock_version
    return f(**args)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3633, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3609, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/minemap/views/minemap.tpl", line 47, in <module>
    %columns = collections.Counter(columns)
AttributeError: 'module' object has no attribute 'Counter'

Best regard

**Comment by mohierf** [comment]
This error looks like if the standard Python module `collections` did not have the `Counter` method ... very strange indeed !

Which version of Python are you using?

I made some tests (end even some patches in the template source ...) and did not get to reproduce your problem ...

**Comment by hvad** [comment]
Hi, 
I use python 2.6.6 on centos 6.
Best regard

**Comment by mohierf** [comment]
Problem confirmed with Python < 2.7 ...
