### ISSUE TITLE
'Webui_broker' object has no attribute 'get_search_string'

### ISSUE THREAD

**Issue by David-** [shinken-monitoring/mod-webui#420]
Hello,

I've just updated shinken (in 2.4.2) and webui2 (shinken install webui2) on my Debian Jessy.
When I try to open WebUI2, I get:
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://supervision.phalippou-frayssinet.fr:7767/dashboard' caused an error:

Internal Server Error

Exception:

AttributeError("'Webui_broker' object has no attribute 'get_search_string'",)

Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    self.global_lock.release()
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3391, in execute
    return self._include(env, subtpl, **rargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3376, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/views/layout.tpl", line 113, in <module>
    %include("header_element")
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3376, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/views/header_element.tpl", line 30, in <module>
    %include("_filters.tpl")
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3376, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/views/_filters.tpl", line 12, in <module>
    %search_string = app.get_search_string()
AttributeError: 'Webui_broker' object has no attribute 'get_search_string'
```
Tell me if you need more info.

Thank you,
David.

**Comment by David-** [comment]
Sorry: a reinstall of the requirements and a reboot made the tricks.
