### ISSUE TITLE
Minemap - 500 internal server error

### ISSUE THREAD

**Issue by jgwinner** [shinken-monitoring/mod-webui#442]
Everything works except for user pref's and the minemap. I get the following error:

Error: 500 Internal Server Error

Sorry, the requested URL 'http://shinken1.example.com:7767/minemap' caused an error:
Internal Server Error

Exception:
AttributeError("'module' object has no attribute 'Counter'",)

Traceback:
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 418, in lock_version
    return f(**args)
  File "/usr/bin/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/bin/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/bin/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/bin/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/minemap/views/minemap.tpl", line 47, in <module>
    %columns = collections.Counter(columns)
AttributeError: 'module' object has no attribute 'Counter'

**Comment by mohierf** [comment]
I am not sur you have the last minemap plugin version ... on line 47 in minemap.tpl (as stated in your error log), there is not this code line ... see https://github.com/shinken-monitoring/mod-webui/blob/develop/module/plugins/minemap/views/minemap.tpl#L47

**Comment by jgwinner** [comment]
Very weird, I used the shinken install command to do it. Once I got the source manually and moved it over, that fixed that. this is a totally fresh install.

Thanks for the quick help

== John ==
