### ISSUE TITLE
Error 500 : IndentationError 'unexpected indent'

### ISSUE THREAD

**Issue by algorys** [shinken-monitoring/mod-webui#459]
Hello @mohierf 

I'm trying to use the webui2 on a new install of Shinken. And I can't log into Shinken WebUI : I can just enter one time my credentials (on `http://localhost:7767/user/login`) and after it only display a 500 error page and can only have access to `http://localhost:7767/dashboard` ... which display : 

```php
Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost:7767/dashboard' caused an error:

Internal Server Error

Exception:

IndentationError('unexpected indent', ('/var/lib/shinken/modules/webui2/views/header_element.tpl', 74, 2, "  if state <= app.hosts_states_critical else 'success'\n"))

Traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 856, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1721, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 418, in lock_version
    return f(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3511, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3487, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3295, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3287, in execute
    return self._include(env, subtpl, **rargs)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3272, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3282, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/views/layout.tpl", line 113, in <module>
    %include("header_element")
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3272, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3282, in execute
    eval(self.co, env)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 186, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3243, in co
    return compile(self.code, self.filename or '<string>', 'exec')
  File "/var/lib/shinken/modules/webui2/views/header_element.tpl", line 74
    if state <= app.hosts_states_critical else 'success'
    ^
IndentationError: unexpected indent
```

The daemon are restart normally and I've just the following error during restart : 

```bash
[1457458572] ERROR: [Shinken] manage_returns exception:: <class 'shinken.http_client.HTTPException'>,Connection error to http://localhost:7768/ : The requested URL returned error: 404 Not Found 
[1457458572] ERROR: [Shinken] manage_returns exception:: <class 'shinken.http_client.HTTPException'>,Connection error to http://localhost:7768/ : The requested URL returned error: 404 Not Found 
[1457458573] ERROR: [Shinken] manage_returns exception:: <class 'shinken.http_client.HTTPException'>,Connection error to http://localhost:7768/ : The requested URL returned error: 404 Not Found 
[1457458574] ERROR: [Shinken] manage_returns exception:: <class 'shinken.http_client.HTTPException'>,Connection error to http://localhost:7768/ : The requested URL returned error: 404 Not Found 
[1457458584] ERROR: [Shinken] Failed sending configuration for receiver-master: Connection error to http://localhost:7773/ : Failed to connect to localhost port 7773: Connection refused
[1457458584] ERROR: [Shinken] [All] Dispatching failed for receiver receiver-master
[1457458587] ERROR: [broker-master] [WebUI-mongo-logs] Exception: Unknown option connect
[1457458587] INFO: [broker-master] [WebUI-logs] configuration, fetching types: ['INFO', 'WARNING', 'ERROR']
```

I've install Shinken like this : 

* Shinken from source. v2.4.2
* Install of requirements : `sudo apt-get install mongodb python-requests python-bottle python-pymongo python-passlib`
* For arrow I've to do with pip : `pip install arrow`
* For webui2 : shinken install webui2

And I put in my broker.cfg : 

```conf
   modules    webui2
```

Is there a problem in source ? Or I've missed something ?

I can provide more information if necessary.

Thanks for help.

**Comment by algorys** [comment]
Sorry, mistake of my part, i've not see version for `pymongo>=3.0.3` and `bottle==0.12.8`.

So it's working.

**Comment by aviau** [comment]
Can you please explain what the issue was? Recent versions of bottle don't work?
