### ISSUE TITLE
No history view on webui2

### ISSUE THREAD

**Issue by jbaptl** [shinken-monitoring/mod-webui#473]
Hello,
I have recently installed shinken 2.4, and the shinken webui2 to surveil multiple devices on 3 differente sites.
I thank you, the views are very confortable and useful. I really like it.
I have installed `pymongo` and `mongodb-org` on the server contening the arbiter and the broker to store logs and have history of events.

```
rpm -qa | grep mongo
python-pymongo-2.5.2-3.el6.x86_64
mongodb-org-mongos-2.6.11-1.x86_64
mongodb-org-server-2.6.11-1.x86_64
mongodb-org-shell-2.6.11-1.x86_64
mongodb-org-2.6.11-1.x86_64
mongodb-org-tools-2.6.11-1.x86_64
```

I followed instructions on pages 
https://github.com/shinken-monitoring/mod-mongo-logs
and 
https://github.com/shinken-monitoring/mod-mongo-logs

But, i have neither Logs view on http://<IP>:7767/logs nor history view on the webui.
The log view, (after deleting line mentionned on a older issue) display following message 
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 1727, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    return f(**args)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3614, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3590, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3394, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.6/site-packages/bottle.py", line 3381, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/logs/views/logs.tpl", line 134, in <module>
    %for log in records:
TypeError: 'NoneType' object is not iterable
```
And i have no history tab neither on main summary no on node summary.
When i activate `mongo-log` module for the broker, I have the following erreur on broker logs: 
```
[1459850496] INFO: [broker-master] Trying to init module: mongo-logs
[1459850496] INFO: [broker-master] I'm stopping module u'mongo-logs' (pid=29564)
[1459850496] INFO: [broker-master] Starting external process for instance mongo-logs
[1459850496] INFO: [broker-master] mongo-logs is now started ; pid=29704
[1459850496] INFO: [broker-master] [mongo-logs[29704]]: Now running..
[1459850496] ERROR: [broker-master] [mongo-logs] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Shinken-2.4-py2.6.egg/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/lib/python2.6/site-packages/Shinken-2.4-py2.6.egg/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/var/lib/shinken/modules/mongo-logs/module.py", line 582, in main
    self.open()
  File "/var/lib/shinken/modules/mongo-logs/module.py", line 215, in open
    self.con = MongoClient(self.uri, connect=False)
  File "/usr/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 258, in __init__
    option, value = common.validate(option, value)
  File "/usr/lib64/python2.6/site-packages/pymongo/common.py", line 243, in validate
    value = validator(option, value)
  File "/usr/lib64/python2.6/site-packages/pymongo/common.py", line 39, in raise_config_error
    raise ConfigurationError("Unknown option %s" % (key,))
ConfigurationError: Unknown option connect

[1459850497] ERROR: [broker-master] The external module mongo-logs goes down unexpectedly!
[1459850497] INFO: [broker-master] Setting the module mongo-logs to restart
```
On mongo, only those collections are settings :
```
> db.getCollectionNames()
[ "system.indexes", "ui_user_preferences" ]
```

For your information, shinken is installed on CentOS6.6. 
Default options are set on `mongodb` and `mongo-logs` modules.

Have you got any idea? Tell me if you need more information.
I thank you for your help.

**Comment by jbaptl** [comment]
I had upgraded my pymongo version to 3.2.2. It work now.
Sorry for the inconvenience
