### ISSUE TITLE
Error loading updated module WebUI2 v2.3.2

### ISSUE THREAD

**Issue by pedrojimenez** [shinken-monitoring/mod-webui#483]
I have just installed the new version of WebUI2 (**2.3.2**) on a working version of **Shinken 2.4.2**. It is not loaded by Broker cause a missing module "alignak" ... It is also detected as **(very-)old-style shinken "module"**
<pre>
[1460962042] WARNING: [broker-master] Cannot import webui2..module : No module named alignak_backend_client.client
[1460962042] WARNING: [broker-master] Trying to load '/var/lib/shinken/modules/webui2' as an (very-)old-style shinken "module" : by adding its path to sys.path. This can be (very) bad in case of name conflicts within the files part of /var/lib/shinken/modules/webui2 and others top-level python modules; I'll try to limit that.
[1460962042] ERROR: [broker-master] Could not import bare 'module.py' from /var/lib/shinken/modules/webui2 : No module named alignak_backend_client.client
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/shinken/modules/webui2/module.py", line 82, in <module>
    from frontend import FrontEnd
  File "/var/lib/shinken/modules/webui2/frontend.py", line 55, in <module>
    from alignak_backend_client.client import Backend, BackendException
ImportError: No module named alignak_backend_client.client
</pre>

I see no extra requirements in any file. How could I install the missing needed module ?

Thanks

**Comment by pedrojimenez** [comment]
I have fixed it ... The "requirements" file must be updated ...
<pre>
# pip install alignak_backend_client
</pre>

**Comment by mohierf** [comment]
Sorry for this and thanks for your feedback. 

I will update the `requirements.txt` file and add a protection if the requirements are not satisfied ...

**Comment by pedrojimenez** [comment]
Thanks @mohierf
