### ISSUE TITLE
Plugins broken

### ISSUE THREAD

**Issue by alexstaz** [shinken-monitoring/mod-webui#485]
Hello,

I've updated to latest release 2.3.2 and modules ui-pnp or auth-active-directory are not loaded correctly.
There is no error, but for exemple when you try to login with auth-active-directory it's not used.

Could you help ?

Thanks.

**Comment by mohierf** [comment]
Of course I may help ... but you should provide a little more information.

At first sight, there is not any reason for those modules to be broken :worried: 

**1/** Did you checked your `webui2.cfg` file to be sure that those modules are really declared in it? If you installed with `shinken install webui2`, your configuration file has been replaced with the default one ...

**2/** If all is ok in your `webui2.cfg` file, your should provide some logs ... restart shinken and copy the `brokerd.log` here ...

**Comment by alexstaz** [comment]
In my webui2.cfg I have :
modules auth-active-directory,ui-pnp

When I run brockerd in Debug, here the logs :
[1460988687] INFO: [broker-master] [WebUI] loaded modules [<module type=pnp_webui name=ui-pnp />, <module type=ad_webui name=auth-active-directory />]
[1460988687] DEBUG: [broker-master] [WebUI] searching module containing check_auth
[1460988687] INFO: [broker-master] [WebUI] No module for AuthMetaModule.
[1460988687] DEBUG: [broker-master] [WebUI] searching module containing get_ui_user_preference, set_ui_user_preference, get_ui_common_preference, set_ui_common_preference

If I uncomment line 313 in module.py (self.modules_manager.set_modules(self.modules))
it loads the modules :
[1460988912] INFO: [broker-master] Get an PNP UI module for plugin ui-pnp
[1460988912] DEBUG: [broker-master] [Active Directory UI] Get an Active Directory/OpenLdap UI module for plugin auth-active-directory
[1460988912] INFO: [broker-master] Trying to init module: ui-pnp
[1460988912] INFO: [broker-master] Trying to init module: auth-active-directory
[1460988912] INFO: [broker-master] I correctly loaded the modules: [ui-pnp,auth-active-directory]
[1460988912] INFO: [broker-master] [WebUI] loaded modules [<module type=pnp_webui name=ui-pnp />, <module type=ad_webui name=auth-active-directory />]
[1460988912] DEBUG: [broker-master] [WebUI] searching module containing check_auth
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: ui-pnp
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: auth-active-directory
[1460988912] INFO: [broker-master] [WebUI] Module found: auth-active-directory
[1460988912] DEBUG: [broker-master] [WebUI] searching module containing get_ui_user_preference, set_ui_user_preference, get_ui_common_preference, set_ui_common_preference
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: ui-pnp
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: auth-active-directory
[1460988912] DEBUG: [broker-master] [WebUI] searching module containing get_ui_logs, get_ui_availability
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: ui-pnp
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: auth-active-directory
[1460988912] DEBUG: [broker-master] [WebUI] searching module containing get_graph_uris
[1460988912] DEBUG: [broker-master] [WebUI] searching in module: ui-pnp
[1460988912] INFO: [broker-master] [WebUI] Module found: ui-pnp

So it's load correctly the modules.
But for module auth-active-directory I have :
[1460989160] INFO: [broker-master] [WebUI] Authenticating user 'alexstaz'
[1460989160] INFO: [broker-master] [WebUI] Authenticating user 'alexstaz' with auth-active-directory
[1460989160] DEBUG: [broker-master] [Active Directory UI] Trying to auth by ldap with user alexstaz
[1460989160] DEBUG: [broker-master] [WebUI - datamanager] get_contact, name: None, user: alexstaz
[1460989160] DEBUG: [broker-master] [WebUI - datamanager] get_contacts, name: None
[1460989160] DEBUG: [broker-master] [WebUI - datamanager] got 15 contacts
[1460989160] WARNING: [broker-master] [WebUI] Back trace: Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui2/submodules/auth.py", line 58, in check_auth
    if mod.check_auth(username, password):
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 214, in check_auth
    c = self.app.datamgr.get_contact(user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 759, in get_contact
    return self.get_contacts(user=user, name=name)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 737, in get_contacts
    return self._only_related_to(items, user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 151, in _only_related_to
    if not user or user.is_administrator():
AttributeError: 'str' object has no attribute 'is_administrator'

Thanks for the help

**Comment by mohierf** [comment]
Thanks for reporting...

**1/**: I opened a new issue because the external WebUI modules were no more loaded. Serious bug with this new version :flushed: 

**2/**: concerning the module problem, I will have a look rapidly ... but I never used this authentication module and I cannot test with it (no AD available to test). Stay tuned ...

**Comment by alexstaz** [comment]
Thanks for opening the bug :)

For the 2 you can test with a ldap (I use a ldap).
What I understand, is that on previous version, you check the contact config to get information if he is an admin. Now it asks the module, and this module hasn't this method.

**Comment by mohierf** [comment]
I understand the problem ... on this line (https://github.com/shinken-monitoring/mod-auth-active-directory/blob/master/module/module.py#L220) the AD module uses a function of the datamanager and this function signature has changed.

Bug found and almost solved!

**Comment by mohierf** [comment]
@alexstaz : Should you make a test with my last commit and confirm that you can authenticate ?

**Comment by alexstaz** [comment]
@mohierf tested only by patching with your latest commit, and all is OK ! 
Thank you very much !!

**Comment by alexstaz** [comment]
Just before you release, I have one more little bug, I can't see all widgets to add.
Please see :
![image](https://cloud.githubusercontent.com/assets/5681800/14612647/953d3a2c-0598-11e6-952b-cac6ef86ef69.png)

**Comment by mohierf** [comment]
I do not understand what is the problem with your widgets ? Please add more information and open another issue for this ...
