### ISSUE TITLE
[Bug] Error 500 on Minemap (webui2/debian jessie)

### ISSUE THREAD

**Issue by xila76** [shinken-monitoring/mod-webui#511]
Fresh install from scratch/no update on debian jessie 8.5 amd64
Conf files (for hosts/services/checks/commands/...) are exported from an old nagios install...

Each times i go on http://shinken.###.###:7767/minemap i get this error (for me this page has never worked from initial setup): 

```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://shinken.###.###:7767/minemap' caused an error:

Internal Server Error
Exception:

error('multiple repeat',)
Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 520, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/minemap/views/minemap.tpl", line 123, in <module>
    %s = app.datamgr.get_service(r, c, user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 301, in get_service
    services = self.search_hosts_and_services('type:service host:^%s$ service:^%s$' % (hname, sname), user=user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 508, in search_hosts_and_services
    pat = re.compile(s)
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: multiple repeat
```

**Comment by david-guenault** [comment]
same here with version 2.2 of webui on shinken 2.4 on centos 7

**Comment by mohierf** [comment]
Can you provide a list of your host names please ? I suspect something around specific characters in the host name ...

**Comment by xila76** [comment]
mail send on your gmail address (found on ur github page) the email come from "toutainj" with object "shinken webui issue 511" and the list of hosts is in this email

For others : my host_name list contains some "." or some "-" anyone has already got any issue with these characters ?

**Comment by mohierf** [comment]
I got your list. Is it possible to try without any special characters in the host names ?

**Comment by xila76** [comment]
I just tried to turn all spaces, dots, dashes of "host_name"
still the same error ...
host_name new list sent by email

some others informations that would be usefull for debuging

```
root@shinken:/etc/shinken/hosts# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
root@shinken:/etc/shinken/hosts# shinken --version
shinken 2.4.3
Shinken Web UI, version: 2.4.1
```

```
root@shinken:/etc/shinken/hosts# python --version
Python 2.7.9
```

```
root@shinken:/etc/shinken/hosts# python --version
Python 2.7.9
root@shinken:/etc/shinken/hosts# pip show bottle
---
Name: bottle
Version: 0.12.8
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```

```
root@shinken:/etc/shinken/hosts# cat /var/lib/shinken/modules/webui2/plugins/minemap/views/minemap.tpl
%groupname = 'all'
%groupalias = 'All hosts'
%title = 'Minemap for all hosts'

%helper = app.helper

%search_string = app.get_search_string()

%# Specific content for breadrumb
%rebase("layout", title='Minemap for hosts/services', css=['minemap/css/minemap.css'], js=['minemap/js/jquery.floatThead.min.js'], breadcrumb=[ ['All hosts', '/minemap'] ])


<div id="minemap">
   %if not items:
      <center>
         %if search_string:
         <h3>Bummer, we couldn't find anything.</h3>
         Use the filters or the bookmarks to find what you are looking for, or try a new search query.
         %else:
         <h3>No host or service.</h3>
         %end
      </center>
   %else:
      %#rows and columns will contain, respectively, all different hosts and all different services ...
      %rows = []
      %columns = []

      %for h in items:
         %if h.my_type=='service':
            %if not h.host_name in rows:
               %rows.append(h.host_name)
            %end
            %if not h.get_name() in columns:
               %columns.append(h.get_name())
            %end
         %elif h.my_type=='host':
            %if not h.get_name() in rows:
               %rows.append(h.get_name())
               %for s in h.services:
                  %columns.append(s.get_name() if s.display_name == '' else s.display_name)
               %end
            %end
         %end
      %end
      %rows.sort()
      %try:
      %# For Python < 2.7 ...
      %import collections
      %columns = collections.Counter(columns)
      %columns = [c for c, i in columns.most_common()]
      %except:
      %pass
      %end

      <!-- Problems synthesis -->
      %s = app.datamgr.get_services_synthesis()
      %h = app.datamgr.get_hosts_synthesis()
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Current filtered hosts/services:</h3>
         </div>
         <div class="panel-body">
            <table class="table table-invisible table-condensed">
               <tbody>
                 %if 'type:service' not in search_string:
                  <tr>
                     <td>
                     <b>{{h['nb_elts']}} hosts:&nbsp;</b>
                     </td>

                     %for state in 'up', 'unreachable', 'down', 'pending', 'unknown', 'ack', 'downtime':
                     <td>
                       %label = "%s <i>(%s%%)</i>" % (h['nb_' + state], h['pct_' + state])
                       {{!helper.get_fa_icon_state_and_label(cls='host', state=state, label=label, disabled=(not h['nb_' + state]))}}
                     </td>
                     %end
                  </tr>
                  %end
                  %if 'type:host' not in search_string:
                  <tr>
                     <td>
                        <b>{{s['nb_elts']}} services:&nbsp;</b>
                     </td>

                     %for state in 'ok', 'warning', 'critical', 'pending', 'unknown', 'ack', 'downtime':
                     <td>
                       %label = "%s <i>(%s%%)</i>" % (s['nb_' + state], s['pct_' + state])
                       {{!helper.get_fa_icon_state_and_label(cls='service', state=state, label=label, disabled=(not s['nb_' + state]))}}
                     </td>
                     %end
                  </tr>
                  %end
               </tbody>
            </table>
         </div>
      </div>

      <table class="table table-hover table-condensed table-fixed-header">
         <thead>
            <tr>
               <th></th>
               %for c in columns:
                  <th class="vertical">
                  <div class="rotated-text"><span class="rotated-text__inner">
                     <a href="/all?search=type:service {{c}}">{{c}}</a>
                  </span></div>
                  </th>
               %end
            </tr>
         </thead>
         <tbody>
            %for r in rows:
               %h = app.datamgr.get_host(r, user)
               %if h:
               <tr>
                  <td title="{{h.get_name()}} - {{h.state}} - {{helper.print_duration(h.last_chk)}} - {{h.output}}">
                     <a href="/host/{{h.get_name()}}">
                        {{!helper.get_fa_icon_state(h, useTitle=False)}}
                        {{h.get_name() if h.display_name == '' else h.display_name}}
                     </a>
                  </td>
                  %for c in columns:
                     %s = app.datamgr.get_service(r, c, user)
                     %if s:
                        <td title="{{s.get_name()}} - {{s.state}} - {{helper.print_duration(s.last_chk)}} - {{s.output}}">
                           <a href="/service/{{h.get_name()}}/{{s.get_name()}}">
                              {{!helper.get_fa_icon_state(s, useTitle=False)}}
                           </a>
                        </td>
                     %else:
                        <td>&nbsp;</td>
                     %end
                  %end
               </tr>
               %end
            %end
         </tbody>
      </table>

     <script language="javascript" type="text/javascript" >
       $(document).ready(function(){
         $('table.table-fixed-header').floatThead({});
       });
     </script>
   %end
</div>
```

**Comment by xila76** [comment]
I found the problem!!! it was a service_description named "NSClient ++ version!"
This post really helped me to put me on the track: http://stackoverflow.com/questions/19942314/python-multiple-repeat-error

I close this issue but maybe add info somewhere in the wiki or the installation notes or other than "++" is not recommended in services_description

**Comment by mohierf** [comment]
Thanks for having searched and reported !
