### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hvad** [shinken-monitoring/mod-webui#533]
Bonjour,

Lorsque qu'aucun hote n'existe cliquer sur currently provoque l'erreur ci dessous : 

Exception:
ZeroDivisionError('float division by zero',)

Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(_a, *_ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 521, in lock_version
    return f(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/dashboard/views/currently.tpl", line 571, in <module>
    %pct_known_problems=round(100.0 \* known_problems / h['nb_elts'], 2)
ZeroDivisionError: float division by zero

A priori c'est du à un division par zero.

**Comment by mohierf** [comment]
Seems to be the same as #529. When no hosts exist in Shinken, this error is raised ... but no hosts ? Is it really a good use case for a monitoring system ? :wink:

**Comment by hvad** [comment]
Hi,
I think it's same as #529. It's not a use case but can arrived.  And i think divided by zero is not good thing :p.

**Comment by mohierf** [comment]
You are right @hvad. I kept the issues opened to make a fix in a next version for this ...

**Comment by kp01aj** [comment]
Hi,

I had the same problem.

I solved as follows:

Comment out the validation in the file

/var/lib/shinken/modules/webui2/plugins/dashboard/views/currently.tpl 

On line 626

% Pct_known_problems = round (100.0 \* known_problems / s [ 'nb_elts'], 2) 
Was as follows:

<-!% Pct_known_problems = round (100.0 \* known_problems / s [ 'nb_elts'], 2) ->

Temporary solution until a new version.

**Comment by maethor** [comment]
I'm closing. This is fixed by commit ccdf3134 in the dev branch.
