### ISSUE TITLE
I can't login thourgh auth-active-directory and even there's no error

### ISSUE THREAD

**Issue by ceso** [shinken-monitoring/mod-webui#539]
Hi, first of all, english is a foreign language for me, so sorry if something is strange.

Well i'm trying to set login in shinken against ldap (freeipa), the server where shinken is running is already enrolled to it. I have installed and configured auth-active-directory and webui2, but when I try to authenticate against ldap with a valid user, I can't and even theres no log errors.
While i was searching about my situation, I found this issue that looks similar 

https://github.com/shinken-monitoring/mod-webui/issues/485 that the fix is in https://github.com/shinken-monitoring/mod-webui/issues/486

I check the commit that fix the bug, and compare to the modules i have, but everything is the same than the commit.

In my webui2.cfg the modules I have are auth-active-directory and ui-graphite2, here is part of my brokerd.log

http://pastebin.com/eK1P1FqR

Thanks a lot!!!

Regards!

**Comment by Azef1** [comment]
Hi,
Have you a contact defined in /etc/shinken/contact/contact.cfg without password with name : "llemos"?
In your brokerd.log, i saw: 

> [1472834453] ERROR: [broker-master] [WebUI-auth-cfg-password] You need to have a contact having the same name as your user: llemos

I advise to read this doc: https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-authentication-modules#active-directory--openldap---auth-active-directory 

Problem solved ?

**Comment by ceso** [comment]
Hi,

First of all, I just ignore that line, because, why I'd need define the contact two times? The benefit of LDAP is I could have my users centralized, if I define the users in contacts.cfg and and again define them but in .cfgs, is the same thing that use httpasswd o.O, tl;dr I loss the benefit of use LDAP :| .
And even if you read some of the lines:

[1472834288] INFO: [broker-master] Correctly loaded auth-active-directory as an old-new-style shinken module :|
[1472834288] INFO: [broker-master] Correctly loaded ui-graphite2 as an old-new-style shinken module :|
[1472834288] INFO: [broker-master] Correctly loaded webui2 as an old-new-style shinken module :|
[1472834288] INFO: [broker-master] I correctly loaded the modules: []
[1472834288] INFO: [broker-master] [WebUI] loaded modules []

That is saying, really that any module was loaded!!
Now, I delete the ui-graphite2 from webui2.cfg, and when I restart,  get this:

[1473082769] INFO: [broker-master] Trying to init module: auth-active-directory
[1473082769] INFO: [broker-master] I correctly loaded the modules: [auth-active-directory]
[1473082769] INFO: [broker-master] [WebUI] loaded modules [<module type=ad_webui name=auth-active-directory />]
[1473082769] INFO: [broker-master] [WebUI] Module found: auth-active-directory

So, now auth-active-directory is loaded ok, and now i have errors in the log!

[1473082826] INFO: [broker-master] [WebUI]  user 'llemos' is signing in ...
[1473082826] INFO: [broker-master] [WebUI] Checking authentication for user: llemos
[1473082826] INFO: [broker-master] [WebUI] Requesting authentication for user: llemos
[1473082826] INFO: [broker-master] [WebUI] Authenticating user 'llemos'
[1473082826] INFO: [broker-master] [WebUI] Authenticating user 'llemos' with auth-active-directory
[1473082826] WARNING: [broker-master] [WebUI] Back trace: Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui2/submodules/auth.py", line 58, in check_auth
    if mod.check_auth(username, password):
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 229, in check_auth
    elts = self.find_contact_entry(c)
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 134, in find_contact_entry
    self.connect()
  File "/var/lib/shinken/modules/auth-active-directory/module.py", line 111, in connect
    self.con.simple_bind_s(self.username, self.password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 208, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(_args,_*kwargs)
NO_SUCH_OBJECT: {'desc': 'No such object'}

The line you tall me, not try even with auth-active-directory, try login with auth-cfg-password, and thats isn't what I want

_EDIT:_ Ok, yes, if i define llemos under contacts in a .cfg file i can authenticate, but as i say, thats for me is useless, i loss the benefits of use Ldap if i need define the user in 2 places :| .
I close the issue, but i'll to create a request in auth-active-directory, thanks!
