### ISSUE TITLE
Worldmap  customization

### ISSUE THREAD

**Issue by ThomasBarach** [shinken-monitoring/mod-webui#555]
Hello!

I wonder if it was possible to display only hosts instead of hosts and services. The fact that a dot is red when a service is critical whereas the host is UP annoys me. 

I looked at the source code, but can't figure out how to remove services.

Regards 

Thomas

**Comment by mohierf** [comment]
Which version are you using? the most recent one I suppose?

If so, you may hack the code to get what you want :wink: edit the *plugins/worldmap/views/_worldmap.tpl* file and remove or comment the lines 21-29:
```
        [
          %#for s in h.services:
          /*
          new Service(
            '{{ s.get_name() }}', '{{ s.state }}',
            '{{ !app.helper.get_fa_icon_state(s) }}',
            '{{ !app.helper.get_business_impact_text(s.business_impact) }}',
            {{ str(s.problem_has_been_acknowledged).lower() }},
            '{{ h.get_name() }}'
          ),
          */
          %#end
        ]
```

Each host in the map will have an empty services list.

-----
**Note:** I did not tested this hack... so may be it will raise an error, but I am quite confident that it will be ok

**Comment by ThomasBarach** [comment]
Thanks for answering.

I was not using the latest version, I upgraded the version and tried to hack the code. 

Unfortunately, it raises an error : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 521, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/worldmap/views/worldmap.tpl", line 27, in <module>
    %include("_worldmap")
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3376, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/worldmap/views/_worldmap.tpl", line 24, in <module>
    '{{ s.get_name() }}', '{{ s.state }}',
NameError: name 's' is not defined
```

**Comment by mohierf** [comment]
Ok, got it!

Do not comment but simply remove the lines and only let the brackets:
```
  []
```

**Comment by ThomasBarach** [comment]
Works like a charm ! 

Thanks for your amazing work

**Comment by mohierf** [comment]
You are welcome :wink:
