### ISSUE TITLE
error 500 on contact page.

### ISSUE THREAD

**Issue by ornoone** [shinken-monitoring/mod-webui#594]
## version 

Shinken 2.4.3 — Web User Interface 2.6.1

## problem 

many page give me a error 500 with some templates errors.

### contact

page: /contact/existingcontact
error: NameError("name 'user' is not defined",)
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 509, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3643, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/contacts/views/contact.tpl", line 31, in <module>
    %for item in app.datamgr.get_hosts(user):
NameError: name 'user' is not defined
```

### preferences
page: /user/pref
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 509, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3643, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/user/views/user_pref.tpl", line 96, in <module>
    %for preference in app.prefs_module.get_ui_user_preference(user):
TypeError: 'NoneType' object is not iterable
```

### note

I will work on it to propose a PR this afternoon.

**Comment by maethor** [comment]
As I said in #595, already fixed in my local dev branch. Will be released soon.
