### ISSUE TITLE
Error accessing the "service-group tab"

### ISSUE THREAD

**Issue by kalinikos** [shinken-monitoring/mod-webui#598]
Hello,
i recently uppdate my Webui2 module to version "WEBUI_VERSION = "2.7.1" and now when i try accessing "Service-group tab"(http://my-shinken-server/services-groups) unfortunately i have the error message with the next traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 509, in lock_version
    return f(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/groups/views/services-groups-overview.tpl", line 129, in <module>
    %services = app.datamgr.search_hosts_and_services('type:service sg:"'+group.get_name()+'"', user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 480, in search_hosts_and_services
    items = [i for i in items if i.__class__.my_type == 'service' and group.get_name() in [s.get_name() for s in i.servicegroups()]]
TypeError: 'list' object is not callable

Please, can someone help me with this?

Regards

**Comment by rkruglickyi** [comment]
+1

**Comment by DmytroObertan** [comment]
+1

**Comment by yshalenyk** [comment]
+1

**Comment by yarsanich** [comment]
+1

**Comment by pontostroy** [comment]
+1

**Comment by shellshock1953** [comment]
+1

**Comment by maethor** [comment]
OK OK, +1s will not make me fix it sooner. I will try to fix this tomorrow.

**Comment by maethor** [comment]
Hi @kalinikos 

I just released 2.7.2 which fixes this bug: https://github.com/shinken-monitoring/mod-webui/releases/tag/2.7.2

Thank you for reporting it.
