### ISSUE TITLE
Webui does'nt start

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#687]
Since commit 364e4c8b.

```
[Mon Dec 17 09:01:07 2018] ERROR: [broker-master] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/modulesmanager.py", line 200, in try_instance_init
    inst.init()
  File "/var/lib/shinken/modules/webui2/module.py", line 388, in init
    if self.alignak:
AttributeError: 'Webui_broker' object has no attribute 'alignak'
```

**Comment by mohierf** [comment]
I fix this immediately !

**Comment by mohierf** [comment]
I just pushed a commit to fix this ... sorry for the problem but I was still obliged to switch between several branches to make some tests :/
