### ISSUE TITLE
Error 500 - system parameters view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#696]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 656, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3639, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui2/plugins/system/system.py", line 40, in system_parameters
    configs = sorted(vars(configs[0]).iteritems())
TypeError: vars() argument must have __dict__ attribute
```

This because the system configuration parameters catched from Shinken/Alignak broks are now in dctionaries. A simple refactoring must be done in the parameters view

**Comment by mohierf** [comment]
Moreover, the current parameters view only displays the first received configuration ... even if Shinken has several schedulers, only the first one information is displayed in this view. **Note** that the information provided by all the schedulers are almost the same indeed...
