### ISSUE TITLE
Exception on page count change

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#707]
On the problems view, changing the page items count fomr 25 to 100 raised an exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/module.py", line 659, in lock_version
    return f(**args)
  File "/usr/local/bin/bottle.py", line 3643, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/bin/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/bin/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/local/bin/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/plugins/problems/views/problems.tpl", line 16, in <module>
    %include("_problems_synthesis.tpl", pbs=pbs, search_string=app.get_search_string())
  File "/usr/local/bin/bottle.py", line 3386, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/usr/local/bin/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/plugins/problems/views/_problems_synthesis.tpl", line 15, in <module>
    %if 'type:service' not in search_string:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by mohierf** [comment]
Perharps something related to the query: `http://127.0.0.1:7767/all?step=100` where the *search_string* parameter is not present ?

Note that the problem is also existing when there i no parameter in the URL...

**Comment by mohierf** [comment]
I found out the problem. The *get_search_string* function sometimes return None rather than a string as it should. I will fix this

**Comment by mohierf** [comment]
I also noticed that the navigation element page count is not set correctly when it just changes ... the value remain to the initial value when the page is loaded. I will also fix this

**Comment by maethor** [comment]
Can we close this issue?

**Comment by mohierf** [comment]
It should have been...
