### ISSUE TITLE
Host/Sevice detail crash when using macros in action_url's template

### ISSUE THREAD

**Issue by dgilm** [shinken-monitoring/mod-webui#88]
I get an error clicking on a host. I think it's related to #70 but I'm not sure.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 682, in _handle
    return callback(**args)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 1332, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 517, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2698, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2672, in template
    return TEMPLATES[tpl].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2644, in render
    self.execute(stdout, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2630, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui/plugins/eltdetail/views/eltdetail.tpl", line 137, in <module>
    <li><a id="action-link" href="{{ MacroResolver().resolve_simple_macros_in_string(triplet, elt.get_data_for_checks()) }}" target=_blank>{{ MacroResolver().resolve_simple_macros_in_string(triplet, elt.get_data_for_checks()) }}</a></li>
  File "/usr/local/lib/python2.7/dist-packages/shinken/macroresolver.py", line 213, in resolve_simple_macros_in_string
    if macro in self.output_macros:
AttributeError: 'MacroResolver' object has no attribute 'output_macros'
```
I can reproduce the error in a python console, executing MacroResolver the way is executed in the eltdetail template. Look:

```
>>> from shinken.macroresolver import MacroResolver
>>> from shinken.objects.host import Host
>>> h=Host() 
>>> hosts = [h]
>>> hosts
[<shinken.objects.host.Host object at 0x1a8ff00>]
>>> MacroResolver().resolve_simple_macros_in_string("blabla", hosts)
'blabla'
>>> MacroResolver().resolve_simple_macros_in_string("$HOSTNAME$", hosts)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/shinken/macroresolver.py", line 213, in resolve_simple_macros_in_string
    if macro in self.output_macros:
AttributeError: 'MacroResolver' object has no attribute 'output_macros'
```

MacroResolver isn't able to translate host macros due output_macros isn't filled because the method init (which is responsible of setting up a lot of variables, one of them output_macros) is never called.

So, It's imposible to use an "action_url" at a template with macros, for example:

```
action_url                      ../../pnp4nagios/graph?host=$HOSTNAME$
```

Why the init() method isn't called? Why don't use Macroresolver as an object (with its constructor) instead of used as a Class object with a fake constructor that it's never called? I'll try to figure out.

**Comment by mohierf** [comment]
Closing ... future release fixes.
